In [1]:
import numpy as np
import pandas as pd

# 1. Insert: The insert function is used for adding new column to a dataframe in any position.

In [51]:
dict = {"Name": ["Tolulope", "Ibukun", "Temitope", "Olawale", "Abiola"], "Class":[1,2,5,6,7], "Subject": ["Phy", "Mat","Bio","Che","Eng"]}

In [53]:
Result = pd.DataFrame(dict)
Result

Name  Class Subject
0  Tolulope      1     Phy
1    Ibukun      2     Mat
2  Temitope      5     Bio
3   Olawale      6     Che
4    Abiola      7     Eng

In [57]:

SubTrack1 =  [54.00, 31.02, 78.32, 83.5, 52.4]

In [55]:
Result.columns

Index(['Name', 'Class', 'Subject'], dtype='object')

In [56]:
Result.info

<bound method DataFrame.info of        Name  Class Subject
0  Tolulope      1     Phy
1    Ibukun      2     Mat
2  Temitope      5     Bio
3   Olawale      6     Che
4    Abiola      7     Eng>

In [65]:
Result.insert(3,'Best_Graduant',SubTrack1)
Result

Name  Class Subject  Best_Graduant   user  Best_Students  Students
0  Tolulope      1     Phy          54.00  54.00          54.00     54.00
1    Ibukun      2     Mat          31.02  31.02          31.02     31.02
2  Temitope      5     Bio          78.32  78.32          78.32     78.32
3   Olawale      6     Che          83.50  83.50          83.50     83.50
4    Abiola      7     Eng          52.40  52.40          52.40     52.40

# 2. Drop Function: The drop() function to drop one or more columns from a pandas DataFrame

In [69]:
Result.drop('Students', axis=1, inplace=True)
Result

Name  Class Subject  Best_Graduant   user
0  Tolulope      1     Phy          54.00  54.00
1    Ibukun      2     Mat          31.02  31.02
2  Temitope      5     Bio          78.32  78.32
3   Olawale      6     Che          83.50  83.50
4    Abiola      7     Eng          52.40  52.40

# 3. Pandas Head Function: The head() function to view the first n rows of a pandas DataFrame.

In [70]:
s3 = pd.Series([20,40,60])
print(s3)
print(type(s3))



0    20
1    40
2    60
dtype: int64
<class 'pandas.core.series.Series'>


In [87]:
s4 = pd.DataFrame([[2,6],[4,5]], columns= ["F","G"], index =["W", "Y"])
print(s4)
print(type(s4))

   F  G
W  2  6
Y  4  5
<class 'pandas.core.frame.DataFrame'>


In [96]:
s5=pd.DataFrame(np.random.randn(20,6),columns=["F","G","W", "Y","K","M"])
s5[(5<s5.index) & (s5.index<10)]

F         G         W         Y         K         M
6 -0.064008 -0.615010  0.895380  1.709370  0.454478  0.879303
7  0.924502  1.062428 -1.116206 -1.079386  0.234978  0.037442
8 -0.106692  1.175990 -1.043631  1.344642 -0.924636  1.724870
9  1.634474 -0.650158 -0.419224  0.222185  1.720921  0.084922

In [97]:
s5.head()

F         G         W         Y         K         M
0  0.859794 -0.421845 -0.062756  1.605158 -2.629584  0.644810
1  0.900144 -0.516430  1.742249  0.839396 -0.916838 -0.671933
2  0.217099  0.945797  0.239012 -0.372177  0.488118 -0.808752
3  1.483238  0.430690 -0.827549  0.281359 -1.598215  0.140505
4  0.049205 -1.443599 -1.008657  2.545008 -0.620304  0.032923

# 4. Tail Function: The tail function in Python displays the last five rows of the dataframe by default.

In [98]:
s5.tail()

F         G         W         Y         K         M
15  0.596921 -1.137028 -1.115583 -0.207871 -0.202211  0.028453
16 -0.325580 -0.322302  0.336853 -0.750022  0.445714  0.632195
17 -0.398078  0.162387 -1.012714  0.029198 -0.652443  0.978022
18  0.062090 -0.570846 -0.394584 -0.239513 -1.235929  0.367610
19 -0.870421 -0.991220 -0.909445 -0.051585  0.402074  0.834901

# 5. Describe Function: Pandas DataFrame describe() method is used to calculate some statistical data such as percentile, mean and std of different numerical values of the DataFrame.

In [99]:
s5.describe()

F          G          W          Y          K          M
count  20.000000  20.000000  20.000000  20.000000  20.000000  20.000000
mean    0.203374  -0.107118  -0.183736   0.095702  -0.149776   0.181848
std     0.792160   0.873507   0.931681   1.084749   1.130984   0.767304
min    -1.550913  -1.443599  -1.788268  -1.589066  -2.629584  -2.006739
25%    -0.331087  -0.623797  -1.009672  -0.649800  -0.918788   0.024634
50%     0.055648  -0.318951  -0.228670  -0.011194   0.252079   0.104010
75%     0.869882   0.550766   0.375986   0.562371   0.550487   0.635349
max     1.634474   1.442605   1.742249   2.545008   1.720921   1.724870

# 6. iloc Function: The “iloc” in pandas is used to select rows and columns by number (index), in the order that they appear in the DataFrame. 

In [100]:
s5.iloc[0:3]

F         G         W         Y         K         M
0  0.859794 -0.421845 -0.062756  1.605158 -2.629584  0.644810
1  0.900144 -0.516430  1.742249  0.839396 -0.916838 -0.671933
2  0.217099  0.945797  0.239012 -0.372177  0.488118 -0.808752

# 7. Loc Function: The Pandas loc method enables you to select data from a Pandas DataFrame by label. It allows you to “ locate” data in a DataFrame.

In [107]:
s5.loc[[2,3],["F","G"]]

F         G
2  0.217099  0.945797
3  1.483238  0.430690

# 8. Mean Function: Pandas dataframe.mean() function return the mean of the values for the requested axis.

In [108]:
s5.mean()

F    0.203374
G   -0.107118
W   -0.183736
Y    0.095702
K   -0.149776
M    0.181848
dtype: float64

# 9. Value_Counts(): Value_counts() returns a Series containing the counts of unique values.

In [110]:
s5["W"].value_counts()

 0.336853    1
-0.394584    1
 0.239012    1
-1.012714    1
 1.063913    1
-0.909445    1
-1.043631    1
-0.827549    1
-0.419224    1
-1.116206    1
-1.788268    1
-1.115583    1
 1.026198    1
 0.895380    1
 0.363034    1
 1.742249    1
-0.057589    1
-1.008657    1
-0.062756    1
 0.414842    1
Name: W, dtype: int64

# 10. drop_duplicates(): This returns a Pandas DataFrame with duplicate rows removed.

In [112]:
s5.drop_duplicates(inplace=True)

# 11. groupby()

Groupby() is used to group a Pandas DataFrame by 1 or more columns, and perform mathematical operation on it. groupby() can be used to summarize data in a simple manner.

# s5.groupby(by='W').Y.mean()

# 11. numpy.repeat

The numpy.repeat(a, repeats, axis=None) function repeats the elements of an array. The number of repetitions is specified by the second argument repeats.

In [116]:
np.repeat(40,5)

array([40, 40, 40, 40, 40])

# 12. numpy.random.randint

The numpy.random.randint(low, high=None, size=None, dtype=’l’) function returns random integers from the interval [low,high). If high parameter is missing (None), the random numbers are selected from the interval [0,low).

In [118]:
np.random.randint(4)

1

# 13. numpy.random.choice

The numpy.random.choice(a, size=None, replace=True, p=None) returns a random sample from a given array. By default, a single value is returned. To return more elements, the output shape can be specified in the parameter size as we did before with the numpy.random.randint function.

In [120]:
np.random.choice([5,6,7,8,9,34])

9

In [125]:
np.random.binomial (10,0.2)

1

# 14. numpy.argmax

The numpy.argmax(a, axis=None, out=None) function returns the indices of the maximum values along an axis.

In [126]:
array = np.array([[2,3,6],[7,8,9]])

In [129]:
max_pos = np.argmax(array)
max_pos

5

# 15. numpy.squeeze

The numpy.squeeze(a, axis=None) removes single-dimensional entries from the shape of an array. The argument axis specifies the axis we want to squeeze out. If the shape of the selected axis is greater than 1 a ValueError is raised.

In [137]:
arr = np.array([[[1],[1]]])

In [138]:
arr.shape

(1, 2, 1)

In [139]:
arr0 = np.squeeze(arr,axis=0)
arr0

array([[1],
       [1]])

In [140]:
arr0.shape

(2, 1)

In [143]:
arr2 = np.squeeze(arr,axis=2)

# 16. The Numpy maximum function

The Numpy max function identifies the maximum value in a Numpy array. 

In [144]:
np.maximum(3,4)

4

# 17. Numpy.Clip Function

The numpy.clip () that can be used to clip the values in an array.

In [146]:
gvn_arry = np.array([1, 3, 6, 8, 9, 14, 16, 30, 42]).reshape(3,3)
gvn_arry 

array([[ 1,  3,  6],
       [ 8,  9, 14],
       [16, 30, 42]])

In [148]:
clip_arry = np.clip(gvn_arry, 5, 15)
clip_arry

array([[ 5,  5,  6],
       [ 8,  9, 14],
       [15, 15, 15]])

# 18. ndarray.shape

The ndarray.shape defines the dimensions of the array.

In [149]:
Books = np.array([[24,40,60],[30,50,90]])
print(Books.shape)

(2, 3)


# 19. ndarray.reshape()

NumPy also provides a reshape() function that reshapes an array.

In [151]:
Work = Books.reshape(3,2)
print(Work)

[[24 40]
 [60 30]
 [50 90]]


# 20. ndarray.itemsize

This returns the size (in bytes) of each element in the array

In [152]:
x = np.array([100,270,350,64,5200], dtype = np.int8)
print(x.itemsize)


1
